Feature 71 confirm dialog before auth
Metatavu/metaform-ui pull request #77
Opened 2021-10-13 14:01 UTC by EVP1989

Resolves #73

2021-10-14 13:03 UTC, Chi-Chu319 commented on src/components/generic/auth-redirect-dialog.tsx
> +  }
```suggestion
  constructor(props: Props) {
    super(props);
    this.state = {};
  }
```

2021-10-14 13:04 UTC, Chi-Chu319 commented on src/components/generic/auth-redirect-dialog.tsx
> +      >
```suggestion
      <Dialog
        open
        BackdropProps={{ style:{ backgroundColor: "#fff", paddingBottom:"100px" }} }
      >
```

2021-10-14 13:05 UTC, Chi-Chu319 commented on src/reducers/auth.ts
> +import { AccessToken, SignedToken } from '../types';
use double quote

2021-10-14 13:06 UTC, Chi-Chu319 requested changes
few suggestions

2021-10-15 11:54 UTC, anttileppa approved these changes

2021-10-15 11:54 UTC, anttileppa commented on src/components/containers/signed-token-refresh.tsx
> +
```suggestion
```

2021-10-15 11:54 UTC, anttileppa commented on src/components/containers/signed-token-refresh.tsx
> +    if (error) {
Move this above the logic

2021-10-15 11:57 UTC, Chi-Chu319 approved these changes

2021-10-18 05:23 UTC, merged